apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- sealedsecrets/sealedsecret-listmonk.yaml
- mailpit

# Cambia estos valores para apuntar a tu GHCR
images:
- name: ghcr.io/REPLACE_ME/listmonk2-app
  newName: ghcr.io/jluisreyvargas/listmonk2-app
  newTag: sha-fed5816e907e24bc55003084075d2ab6eda6caea
- name: ghcr.io/jluisreyvargas/listmonk2
  newName: ghcr.io/jluisreyvargas/listmonk2
  newTag: sha-2fe5aa4d7d6e1a60e3053eabb0bf85a612dc62a5
