apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - sealedsecrets/sealedsecret-listmonk.yaml

# Cambia estos valores para apuntar a tu GHCR
images:
  - name: ghcr.io/jluisreyvargas/listmonk2-app
    newName: ghcr.io/jluisreyvargas/listmonk2-app
    newTag: sha-fed5816e907e24bc55003084075d2ab6eda6caea
